### ISSUE TITLE
Sho3'l Cairo

### ISSUE THREAD

**Issue by gr33ndata** [Pyeg/Ideas#10]
A page with a map for startups, investors and code development shops in Cairo (or Egypt), something a la:

http://www.builtinlondon.co/
http://mappedinny.com/
http://madeinnyc.org/
http://mappedinisrael.com/
http://www.israelimappedinny.com/
http://mappedinsiliconvalley.com/

This can be as simple as a github page by the way, we can use json files as our database.

**Comment by mtayseer** [comment]
Already there? http://startupmap.info/

**Comment by gr33ndata** [comment]
Ok, good to know there is one already

**Comment by mos3abof** [comment]
Its source code is open if anyone is interested for any other project : https://github.com/abenzer/represent-map
