### ISSUE TITLE
Aptana Full Web IDE with Git Support!

### ISSUE THREAD

**Issue by thigazi** [Pyeg/Ideas#12]
Hi people!
As I am using aptana (aptana.com), which is based on eclipse, I have figured out that it has full GIT Support for push commit and request out of the box. 

Aptana is my standard development environment, which comes with a sophisticated Web Editor, Javascript Editor, PHP, Python and Ruby Editor out of the box.

Download eclipse (naked) without any tools, for:

Linux 64-Bit:
ftp://mirror.switch.ch/mirror/eclipse/eclipse/downloads/drops4/R-4.3.1-201309111000/eclipse-platform-4.3.1-linux-gtk-x86_64.tar.gz

Linux 32-Bit:
ftp://mirror.switch.ch/mirror/eclipse/eclipse/downloads/drops4/R-4.3.1-201309111000/eclipse-platform-4.3.1-linux-gtk.tar.gz

Windows 32-Bit:
ftp://mirror.switch.ch/mirror/eclipse/eclipse/downloads/drops4/R-4.3.1-201309111000/eclipse-platform-4.3.1-win32.zip

Windows 64-Bit:
ftp://mirror.switch.ch/mirror/eclipse/eclipse/downloads/drops4/R-4.3.1-201309111000/eclipse-platform-4.3.1-win32-x86_64.zip

and install through the update manager:
http://download.aptana.com/studio3/plugin/install

Have fun!

Tamer

**Comment by gr33ndata** [comment]
Thanks for the recommendation Tamer.
