### ISSUE TITLE
Rename it to "Code for Egypt" instead if "PyEg"

### ISSUE THREAD

**Issue by mtayseer** [Pyeg/Ideas#2]
1. While we all love Python, choice of technology should be based on the best for the project itself. If Python is the best, we have to prove it.
2. We can engage a larger number of people.
3. It will allow us to solve a broader range of problems.

**Comment by gr33ndata** [comment]
Good point, but it is hard to collaborate in projects written in languages you do not know. We just gather here python developers, however, each individual of us is ready to collaborate in whatever project in whichever language they find as long as they have the capacity to collaborate there. I'll forward you an email now, why we created this

**Comment by thigazi** [comment]
@gr33ndata is absolutely right!

We are a python community. "pyeg" is ment for "Python Egypt". As well I saw in PythonLocalUsers Egypt and Arab World..... "Arab World ?!"

And broader problems need more specialists in other subjects, we need to get the site up for the python stuff, that is already a lot of work......
Totally unrealistic... as well, I think we'd love to moderate things we know at best and have the most joy in. No ?!
