### ISSUE TITLE
Soundcloud Desktop Player

### ISSUE THREAD

**Issue by mos3abof** [Pyeg/Ideas#8]
I always wanted to create a desktop player for my soundcloud stream using soundcloud's API :)

**Comment by gr33ndata** [comment]
My main problem with Sound Cloud is that it doesn't Scrobble to Last.fm, it would be nice if the Desktop player can o that

**Comment by mos3abof** [comment]
I am not actually sure of the API's capabilities yet :)

**Comment by mahmoudhossam** [comment]
The SoundCloud API does allow [streaming](http://developers.soundcloud.com/docs/api/guide#streaming) as long as you follow the rules in the link.

Also, after looking at their [apps](http://soundcloud.com/apps), it seems that songbird already does that, and I think it also scrobbles to Last.fm.

**Comment by mos3abof** [comment]
@mahmoudhossam & @gr33ndata , should we close this issue then?

**Comment by mahmoudhossam** [comment]
I vote to close, unless you guys have anything you'd like to add.
